### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by taylorgoolsby** [migalooo/glsl-shader-loader#1]
To the creator: 

Hi, I was wondering if you still use this package and if it's still actively maintained?

I think it's a great idea that your loader both allows for nested imports, and prevents duplicate imports. (And the way you import allows us to rename imports to avoid clashes!)

If this is no longer maintained, do you know of another glsl loader which allows nested imports but prevents duplicates?

**Comment by migalooo** [comment]
Thank you for asking. I just use this loader to organize my simple shaders，because I don't have a project that needs to be used it in depth. If there's any problem i will try to fix it, but it may not be very timely, sorry for that😔.
Collaborates are welcome.

**Comment by migalooo** [comment]
Thank you for asking. I just use this loader to organize my simple shaders，because I don't have a project that needs to be used it in depth. If there's any problem i will try to fix it, but it may not be very timely, sorry for that😔.
Collaborates are welcome.
